version: '3'

services:
  server-nginx-certbot:
    # build:
    #   context:      './../../docker/server-nginx-certbot'
    #   dockerfile:   'Dockerfile'
    container_name: 'server-nginx-certbot'
    image:          'talsenteam/docker-nginx-certbot:v1.15-alpine'
    network_mode:   'host'
    restart:        'no'
    volumes:
      -             '${ENV_PATH_VOLUMES_ROOT}/../env/server-nginx-certbot/:/etc/nginx/env:ro'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/cache/:/cache'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/manual-config/:/manual-config:ro'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/etc/letsencrypt/:/etc/letsencrypt'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/var/lib/letsencrypt/:/var/lib/letsencrypt'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/var/log/letsencrypt/:/var/log/letsencrypt'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-nginx-certbot/var/log/nginx/:/var/log/nginx'